/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Esteban
 */
public class Frm_PantallaCarga extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_PantallaCarga.class.getName());

    /**
     * Creates new form Frm_PantallaCarga
     */
    public Frm_PantallaCarga() {
        initComponents();
        try {
            this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_hjk.png")).getImage());
        } catch (Exception e) {
            System.err.println("No se pudo cargar el ícono de la ventana: " + e.getMessage());
        }
        lbl_textoLogo.setText("<html><center>Los Huertos<br>del Juank</center></html>");
        lbl_textoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        try {
            java.io.InputStream is = getClass().getResourceAsStream("/resources/fonts/Albertus Nova.otf");
            Font albertusFont = Font.createFont(Font.TRUETYPE_FONT, is);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(albertusFont);
            Font fuenteTitulo = albertusFont.deriveFont(Font.BOLD, 48f); 
            Font fuenteLeyenda = albertusFont.deriveFont(Font.ITALIC, 14f);
            lbl_textoLogo.setFont(fuenteTitulo);
            lbl_instrucciones.setFont(fuenteLeyenda);
        } catch (Exception e) {
            System.err.println("No se pudo cargar la fuente en la pantalla de carga: " + e.getMessage());
        }
        java.awt.event.ActionListener parpadeoAction = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                lbl_instrucciones.setVisible(!lbl_instrucciones.isVisible());
            }
        };
        javax.swing.Timer timerParpadeo = new javax.swing.Timer(500, parpadeoAction);
        timerParpadeo.start();
        this.setFocusable(true);
        this.requestFocusInWindow();

        this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    timerParpadeo.stop();
                    Frm_Principal principal = new Frm_Principal();
                    principal.setVisible(true);
                    principal.setLocationRelativeTo(null);
                    dispose();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
                    timerParpadeo.stop();
                    System.exit(0);
                }
            }
        });
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_textoLogo = new javax.swing.JLabel();
        lbl_instrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Los Huertos del JuanK");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 235, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 53, 37), 6));
        jPanel1.setForeground(new java.awt.Color(74, 53, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_hjk_230.png"))); // NOI18N

        lbl_textoLogo.setFont(new java.awt.Font("Albertus Nova", 1, 48)); // NOI18N
        lbl_textoLogo.setForeground(new java.awt.Color(74, 53, 37));
        lbl_textoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_textoLogo.setText("<html><center>Los Huertos<br>del Juank</center></html>");
        lbl_textoLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_instrucciones.setFont(new java.awt.Font("Albertus Nova Light", 2, 18)); // NOI18N
        lbl_instrucciones.setForeground(new java.awt.Color(74, 53, 37));
        lbl_instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_instrucciones.setText("Presione [Enter] para continuar o [Esc] para salir.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_textoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_instrucciones)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_textoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lbl_instrucciones)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_PantallaCarga().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_instrucciones;
    private javax.swing.JLabel lbl_textoLogo;
    // End of variables declaration//GEN-END:variables
}
